/mob/living/simple_animal/friendly/owl
	name = "Garronte"
	desc = "When you sleep, he is awake!. In the eyes you can look the future."
	gender = MALE
	health = 25
	maxHealth = 25
	unique_pet = TRUE
	density = 1
	icon = 'icons/hispania/mob/animals.dmi'
	icon_state = "owl"
	icon_living = "owl"
	icon_dead = "owl_dead"
	speak_emote = list("hoot")
	emote_hear = list("hoot")
	emote_see = list("hoot")
	turns_per_move = 10
	can_collar = 0
	gold_core_spawnable = NO_SPAWN
	unique_pet = TRUE