language: generic
dist: xenial
os: linux

git:
  depth: 1

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

env:
  global:
    - BYOND_MAJOR="513"
    - BYOND_MINOR="1505"
    - BYOND_MACRO_COUNT=4
  matrix:
    - DM_MAPFILE="hispania"
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="delta"
    - DM_MAPFILE="test_all_maps"

stages:
  - File Checks
  - test

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
script:
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} paradise.dme

jobs:
  include:
    - name: "Run Linters"
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python3-setuptools
      install:
        - tools/travis/install_build_deps.sh
        - tools/travis/install_dreamchecker.sh
      script:
        - shopt -s globstar
        - find . -name "*.php" -print0 | xargs -0 -n1 php -l
        - find . -name "*.json" -not -path "./nano/node_modules/*" -print0 | xargs -0 python3 ./tools/travis/json_verifier.py
        - tools/travis/build_nanoui.sh
        - tools/travis/check_grep.sh
        - tools/travis/check_changelogs.sh
        - python3 tools/travis/check_line_endings.py
        - ~/dreamchecker

    - name: "Compile All Maps"
      addons:
        apt:
          packages:
            - libstdc++6:i386
      cache:
        directories:
          - $HOME/BYOND
      install:
        - tools/travis/install_byond.sh
        - source $HOME/BYOND/byond/bin/byondsetup
      script:
        - tools/travis/dm.sh -Mtravis_map_testing paradise.dme
